PENDING = "PENDING"
SUCCESS = "SUCCESS"
FAILURE = "FAILURE"
RETRY = "RETRY"

READY_STATES = frozenset([SUCCESS, FAILURE])
UNREADY_STATES = frozenset([PENDING, RETRY])
EXCEPTION_STATES = frozenset([RETRY, FAILURE])

ALL_STATES = frozenset([PENDING, SUCCESS, FAILURE, RETRY])
