#!/bin/bash
base=${1:-.}
nosetests -vd celery.tests                                      \
          --with-coverage3                                      \
            --cover3-branch                                     \
            --cover3-xml                                        \
            --cover3-xml-file="$base/coverage.xml"              \
            --cover3-html                                       \
            --cover3-html-dir="$base/cover"                     \
            --cover3-package=celery                             \
            --cover3-exclude="                                  \
              celery                                            \
              celery.tests.*                                    \
              celery.utils.compat                               \
              celery.utils.dispatch*                            \
              celery.db.a805d4bd                                \
              celery.db.dfd042c7                                \
              celery.contrib*                                   \
              celery.concurrency.threads                        \
              celery.concurrency.gevent                         \
              celery.backends.mongodb                           \
              celery.backends.cassandra                         \
              celery.events.cursesmon"                          \
            --with-xunit                                        \
              --xunit-file="$base/nosetests.xml"
