# These are supported funding model platforms

github:
patreon:
open_collective: celery
ko_fi: # Replace with a single Ko-fi username
tidelift: pypi/celery
custom: # Replace with a single custom sponsorship URL
