BROKER_HOST = "localhost"
BROKER_PORT = 5672
BROKER_USER = "guest"
BROKER_PASSWORD = "guest"
BROKER_VHOST = "/"

CELERY_RESULT_BACKEND = "database"
CELERY_RESULT_DBURI = "sqlite:///:memory:"
CELERY_SEND_TASK_ERROR_EMAILS = False
