#!/bin/bash
base=${1:-.}
nosetests -vd celery.tests                                      \
          --with-coverage3                                      \
            --cover3-branch                                     \
            --cover3-xml                                        \
            --cover3-xml-file="$base/coverage.xml"              \
            --cover3-html                                       \
            --cover3-html-dir="$base/cover"                     \
            --cover3-package=celery                             \
            --cover3-exclude="celery.tests.*"                   \
          --with-xunit                                          \
            --xunit-file="$base/nosetests.xml"
