{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app: {{ include "..fullname" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
