#!/usr/bin/env python

import os
import os.path
from typing import Iterable

import yaml

# The name of the Python cache directory, where byte-compiled *.pyc files are
# stored.
PYCACHE_DIRECTORY_NAME = '__pycache__'

# The prefix used by test modules in t/integration and t/smoke.
TEST_MODULE_PREFIX = 'test_'

# The path to the "Celery" GitHub workflow
GITHUB_WORKFLOW_CELERY = ".github/workflows/python-package.yml"

# The repository root, as inferred by the path to this module
REPOSITORY_ROOT = os.path.join(os.path.dirname(__file__), "..")


def filter_test_module_filenames(filenames: Iterable[str]) -> set[str]:
    """Select test module filenames from the provided filenames.

    Arguments:
        filenames (Iterable of Strings): the filenames to filter

    Returns:
        Set: Set of filenames matching the filter
    """

    test_module_filenames: set[str] = set()
    for filename in filenames:
        # Only match `test_*.py`
        _, extension = os.path.splitext(filename)
        if extension != ".py":
            continue
        if not filename.startswith(TEST_MODULE_PREFIX):
            continue

        test_module_filenames.add(filename)

    return test_module_filenames


def find_test_module_filenames(root: str) -> set[str]:
    """Recurse through root to get all the test module filenames.

    Arguments:
        root (String): the root directory relative to the repository root
                       containing the test modules

    Returns:
        Set: Set of test module filenames
    """
    root = os.path.join(REPOSITORY_ROOT, root)
    all_test_module_filenames: set[str] = set()
    for _, dirnames, filenames in os.walk(root):
        # Prune the __pycache__ directory from the directories to traverse.
        if PYCACHE_DIRECTORY_NAME in dirnames:
            dirnames.remove(PYCACHE_DIRECTORY_NAME)

        # Add the filtered test modules from this prefix to the full list
        all_test_module_filenames |= filter_test_module_filenames(filenames)

    return all_test_module_filenames


def assert_matches(
    left: set[str], left_name: str,
    right: set[str], right_name: str,
) -> None:
    """Assert that the filenames in left are the same as those in right.

    If the filenames in left are not the same as those in right, an
    AssertionError is raised with a message explaining the mismatch.

    Arguments:
        left (Set of Strings): the set of the filenames on the left
        left_name (String): the name for the left set
        right (Set of Strings): the set of the filenames on the right
        right_name (String): the name for the right set
    """

    not_in_right = left - right
    assert not not_in_right, (
        f"The following test modules in {left_name} are not " +
        f"present in {right_name}: " +
        " ".join([repr(filename) for filename in not_in_right])
    )
    not_in_left = right - left
    assert not not_in_left, (
        f"The following test modules in {right_name} are not " +
        f"present in {left_name}: " +
        " ".join([repr(filename) for filename in not_in_left])
    )


def check_test_filenames(gh_workflow: dict, job_name: str, root: str) -> None:
    """Check that the filenames in the workflow job match those found in root.

    Arguments:
        gh_workflow (Dictionary): the parsed GitHub workflow
        job_name (String): the name of the workflow job
        root (String): the path to the root of the test directory
    """

    workflow_matrix_filenames = set(
        gh_workflow["jobs"][job_name]["strategy"]["matrix"]["module"]
    )
    found_filenames = find_test_module_filenames(root)
    assert_matches(
        workflow_matrix_filenames,
        f"the {job_name} matrix in {GITHUB_WORKFLOW_CELERY}",
        found_filenames,
        root,
    )


def main():
    """Run the check for smoke and integration test filenames."""

    # Load the "Celery" GitHub workflow as a Python object
    gh_workflow_path = os.path.join(REPOSITORY_ROOT, GITHUB_WORKFLOW_CELERY)
    with open(gh_workflow_path) as f:
        gh_workflow = yaml.load(f, yaml.Loader)

    # Ensure that our parsed workflow is a dictionary, it still might not
    # conform to what check_test_filenames expects, but this is the easiest
    # check we can do for coherence.
    assert isinstance(gh_workflow, dict)

    check_test_filenames(gh_workflow, "Integration-tests", "t/integration")
    check_test_filenames(gh_workflow, "Smoke-tests", "t/smoke/tests")


if __name__ == "__main__":
    main()
