#!/bin/bash -e
# ============================================
#  celeryd - Starts the Celery worker daemon.
# ============================================
#
# :Usage: /etc/init.d/celeryd {start|stop|force-reload|restart|try-restart|status}
#
# :Configuration file: /etc/default/celeryd
#
# To configure celeryd you probably need to tell it where to chdir.
#
# EXAMPLE CONFIGURATION
# =====================
#
# this is an example configuration for a Python project:
#
# /etc/default/celeryd:
#
#   # Where to chdir at start.
#   CELERYD_CHDIR="/opt/Myproject/"
#
#   # Extra arguments to celeryev
#   CELERYEV_OPTS="-x"
#
#   # Name of the celery config module.#
#   CELERY_CONFIG_MODULE="celeryconfig"
#
#   # Camera class to use (required)
#   CELERYEV_CAM = "myapp.Camera"
#
# EXAMPLE DJANGO CONFIGURATION
# ============================
#
#   # Where the Django project is.
#   CELERYD_CHDIR="/opt/Project/"
#
#   # Name of the projects settings module.
#   export DJANGO_SETTINGS_MODULE="settings"
#
#   # Path to celeryd
#   CELERYEV="/opt/Project/manage.py"
#
#   # Extra arguments to manage.py
#   CELERYEV_OPTS="celeryev"
#
#   # Camera class to use (required)
#   CELERYEV_CAM = "djcelery.snapshot.Camera"
#
# AVAILABLE OPTIONS
# =================
#
#   * CELERYEV_OPTS
#       Additional arguments to celeryd, see `celeryd --help` for a list.
#
#   * CELERYD_CHDIR
#       Path to chdir at start. Default is to stay in the current directory.
#
#   * CELERYEV_PID_FILE
#       Full path to the pidfile. Default is /var/run/celeryd.pid.
#
#   * CELERYEV_LOG_FILE
#       Full path to the celeryd logfile. Default is /var/log/celeryd.log
#
#   * CELERYEV_LOG_LEVEL
#       Log level to use for celeryd. Default is INFO.
#
#   * CELERYEV
#       Path to the celeryev program. Default is `celeryev`.
#       You can point this to an virtualenv, or even use manage.py for django.
#
#   * CELERYEV_USER
#       User to run celeryev as. Default is current user.
#
#   * CELERYEV_GROUP
#       Group to run celeryev as. Default is current user.
#
#   * VIRTUALENV
#       Full path to the virtualenv environment to activate. Default is none.

### BEGIN INIT INFO
# Provides:          celeryev
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: celery event snapshots
### END INIT INFO

set -e

DEFAULT_PID_FILE="/var/run/celeryev.pid"
DEFAULT_LOG_FILE="/var/log/celeryev.log"
DEFAULT_LOG_LEVEL="INFO"
DEFAULT_CELERYEV="/usr/bin/celeryev"

if test -f /etc/default/celeryd; then
    . /etc/default/celeryd
fi

if test -f /etc/default/celeryev; then
    . /etc/default/celeryev
fi

CELERYEV=${CELERYEV:-$DEFAULT_CELERYEV}
CELERYEV_PID_FILE=${CELERYEV_PID_FILE:-${CELERYEV_PIDFILE:-$DEFAULT_PID_FILE}}
CELERYEV_LOG_FILE=${CELERYEV_LOG_FILE:-${CELERYEV_LOGFILE:-$DEFAULT_LOG_FILE}}
CELERYEV_LOG_LEVEL=${CELERYEV_LOG_LEVEL:-${CELERYEV_LOG_LEVEL:-$DEFAULT_LOG_LEVEL}}

export CELERY_LOADER

. /lib/lsb/init-functions

CELERYEV_OPTS="$CELERYEV_OPTS -f $CELERYEV_LOG_FILE -l $CELERYEV_LOG_LEVEL"

if [ -z "$CELERYEV_CAM" ]; then
    echo "Missing CELERYEV_CAM variable" 1>&2
    exit
fi

CELERYEV_OPTS="$CELERYEV_OPTS -c $CELERYEV_CAM"

if [ -n "$2" ]; then
    CELERYEV_OPTS="$CELERYEV_OPTS $2"
fi

# Extra start-stop-daemon options, like user/group.
if [ -n "$CELERYEV_USER" ]; then
    DAEMON_OPTS="$DAEMON_OPTS --chuid $CELERYEV_USER"
fi
if [ -n "$CELERYEV_GROUP" ]; then
    DAEMON_OPTS="$DAEMON_OPTS --group $CELERYEV_GROUP"
fi

if [ -n "$CELERYEV_CHDIR" ]; then
    DAEMON_OPTS="$DAEMON_OPTS --chdir $CELERYEV_CHDIR"
elif [ -n "$CELERYD_CHDIR" ]; then
    DAEMON_OPTS="$DAEMON_OPTS --chdir $CELERYD_CHDIR"
fi


# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}


check_dev_null() {
    if [ ! -c /dev/null ]; then
    if [ "$1" = log_end_msg ]; then
        log_end_msg 1 || true
    fi
    if ! run_by_init; then
        log_action_msg "/dev/null is not a character device!"
    fi
    exit 1
    fi
}


export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"


stop_evcam () {
    cmd="start-stop-daemon --stop \
                           --quiet \
                           $* \
                           --pidfile $CELERYEV_PID_FILE"
    if $cmd; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
}

start_evcam () {
    cmd="start-stop-daemon --start $DAEMON_OPTS \
                           --quiet \
                           --oknodo \
                           --background \
                           --make-pidfile \
                           $* \
                           --pidfile $CELERYEV_PID_FILE
                           --exec $CELERYEV -- $CELERYEV_OPTS"
    if [ -n "$VIRTUALENV" ]; then
        source $VIRTUALENV/bin/activate
    fi
    if $cmd; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
}



case "$1" in
  start)
    check_dev_null
    log_daemon_msg "Starting celery event snapshots" "celeryev"
    start_evcam
    ;;
  stop)
    log_daemon_msg "Stopping celery event snapshots" "celeryev"
    stop_evcam --oknodo
    ;;

  reload|force-reload)
    echo "Use start+stop"
    ;;

  restart)
    log_daemon_msg "Restarting celery event snapshots" "celeryev"
    stop_evcam --oknodo --retry 30
    check_dev_null log_end_msg
    start_evcam
    ;;

  try-restart)
    log_daemon_msg "Restarting celery event snapshots" "celeryev"
    set +e
    stop_evcam --retry 30
    RET="$?"
    set -e
    case $RET in
        0)
        # old daemon stopped
        check_dev_null log_end_msg
        start_evcam
        ;;
        1)
        # daemon not running
        log_progress_msg "(not running)"
        log_end_msg 0
        ;;
        *)
        # failed to stop
        log_progress_msg "(failed to stop)"
        log_end_msg 1
        ;;
    esac
    ;;

  status)
    status_of_proc -p $CELERYEV_PID_FILE $CELERYEV celeryev && exit 0 || exit $?
    ;;

  *)
    log_action_msg "Usage: /etc/init.d/celeryev {start|stop|force-reload|restart|try-restart|status}"
    exit 1
esac

exit 0
