name: changerelease
on:
  workflow_dispatch: {}
  push:
    paths: [Changelog.rst]
    branches: [master]
    tags: ["*"]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://pandoc/core:2.9
      with:
        args: "Changelog.rst -f rst -t markdown -o CR_CHANGELOG.md"
    - uses: dropseed/changerelease@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        changelog: CR_CHANGELOG.md
        remote_changelog: false
        limit: -1
