on:
  release:
    types: [released]

permissions: {}
jobs:
  post_release_to_hacker_news:
    runs-on: ubuntu-latest
    name: Post Release to Hacker News
    steps:
      - name: Post the Release
        uses: MicahLyle/github-action-post-to-hacker-news@v1
        env:
          HN_USERNAME: ${{ secrets.HN_USERNAME }}
          HN_PASSWORD: ${{ secrets.HN_PASSWORD }}
          HN_TITLE_FORMAT_SPECIFIER:  Celery v%s Released!
          HN_URL_FORMAT_SPECIFIER: https://docs.celeryq.dev/en/v%s/changelog.html
          HN_TEST_MODE: true
